name: Follow up commenter

on:
  issue_comment:
    types: [created, edited]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Create comment
         uses: peter-evans/create-or-update-comment@v3
         with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          token: ${{ secrets.GITHUB_TOKEN }}
